<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class userSeader extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Admin1',
                'email' => 'admin1@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin2',
                'email' => 'admin2@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin3',
                'email' => 'admin3@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin4',
                'email' => 'admin4@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin5',
                'email' => 'admin5@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin6',
                'email' => 'admin6@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin7',
                'email' => 'admin7@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin8',
                'email' => 'admin8@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin9',
                'email' => 'admin9@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin10',
                'email' => 'admin10@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin11',
                'email' => 'admin11@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin12',
                'email' => 'admin12@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin13',
                'email' => 'admin13@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin14',
                'email' => 'admin14@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin15',
                'email' => 'admin15@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin16',
                'email' => 'admin16@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin17',
                'email' => 'admin17@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin18',
                'email' => 'admin18@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin19',
                'email' => 'admin19@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin20',
                'email' => 'admin20@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin21',
                'email' => 'admin21@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin22',
                'email' => 'admin22@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin23',
                'email' => 'admin23@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin24',
                'email' => 'admin24@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin25',
                'email' => 'admin25@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin26',
                'email' => 'admin26@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin27',
                'email' => 'admin27@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin28',
                'email' => 'admin28@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin29',
                'email' => 'admin29@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin30',
                'email' => 'admin30@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin31',
                'email' => 'admin31@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin32',
                'email' => 'admin32@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin33',
                'email' => 'admin33@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin34',
                'email' => 'admin34@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin35',
                'email' => 'admin35@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin36',
                'email' => 'admin36@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Admin',
                'id_status' => '1',
                'id_departemen' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'User',
                'email' => 'user@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'User',
                'id_status' => '1',
                'id_departemen' => 'Null',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Superadmin',
                'email' => 'superadmin@gmail.com',
                'password' => Hash::make('12345'),
                'id_role' => 'Superadmin',
                'id_status' => '1',
                'id_departemen' => 'Null',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
